### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [taskin744/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_  4 (Exceeds Expectations)
* _Comment(s):_ Every answer includes text and query results (as supporting evidence). Related queries are uploaded in a separate .sql file.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All queries accurately retrieve the data intended (as stated or implied by comments or the presentation).
 
### Criteria 3: Query Formatting
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Queries adhere to at least 7 rules of the style guide. I was unable to view your raw .sql file (there were two files uploaded of your code, one which was a pdf file and the other which seemed like an html file of some sort). I looked at the pdf file because that was the more readable version. Typically, expressions like "AND" are put on new lines and when ending a statement (with a comma), the following text is placed on a new line. Also, it's important to capitalize SQL expressions -- AS, AND, SUM, SELECT, etc. -- because that lets readers know what is a variable from the dataset and what's part of the SQL language.
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_4 (Exceeds Expectations)
* _Comment(s):_ Your project demonstrates a clear understanding of churn rates. Terms are used correctly throughout your conclusions. 

 ### Overall Score: 15/16
Overall, great job! Your project shows an in-depth understanding of churn rates and the SQL language. The graphics and tables you added as evidence for each of your conclusions made your presentation easy to follow and understand. The only feedback is on ensuring you follow SQL Query Formatting Guidelines; it is a useful skill to have, especially because it makes it easier to revise your code later on and it makes it easier for others reading your code to understand what the purpose of your query is.

**Comment by taskin744** [comment]
Thank you for reviewing and reflecting on my submission.
